server:
  port: 1145

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myblog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: -1
        min-idle: 0
    timeout: 1000
file:
  upload:
    path: D:/vue/image/
  coming:
    path: http://localhost:80/image/
logging:
  level:
    com:
      sakura:
        myblog:
          mapper:
            debug