server:
  port: 1145

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myblog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sakura
    password: sakura00
  jackson:
    default-property-inclusion: non_null
    date-format: YYYY-MM-dd HH:MM:SS
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: -1
        min-idle: 0
    timeout: 1000
    password: sakura
file:
  upload:
    path: /var/www/image
  coming:
    path: http://senkaryouran.top/
logging:
  level:
    com:
      sakura:
        myblog:
          mapper:
            debug